### ISSUE TITLE
error: [Channel.js]: Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]

### ISSUE THREAD

**Issue by sirishkalidindi** [sindelio/hyperledger-fabric-traceability-framework#33]
while post http://localhost:5000/api/v1/asset  getting these errors

"error": "Unable to initialize channel. Attempted to contact 2 Peers. Last error was Error: 2 UNKNOWN: access denied: channel [mychannel] creator org [Org1MSP]"

![image](https://user-images.githubusercontent.com/6596167/185597764-ac2dbbce-5593-477c-a34f-fb3e5670c639.png)
![image (1)](https://user-images.githubusercontent.com/6596167/185597783-e0643d93-ece2-4412-8867-85ab33a12fa2.png)

Could you please suggest.

Thanks in advance

Sirish K

**Comment by sirishkalidindi** [comment]
its working

**Comment by sindelio** [comment]
Glad you found your way around it, however I advise you to use this code as
a reference only, since I don't have time to give proper maintenance to it.
