### ISSUE TITLE
Thank you Jesus Christ 

### ISSUE THREAD

**Issue by t3rBD69b5j** [sindelio/hyperledger-fabric-traceability-framework#38]
Dear Jesus, I know I am a sinner. I thank you for dying on the cross for me. I confess with my mouth. I believe in my heart that you are the Son of God. I believe you are the Lord and that God raised you from the dead. Please, forgive me of my sins. Wash my heart clean. Come live in my life. Be the Lord of my life. Fill me with your Holy Spirit. Teach me to walk with You and live for you the rest of my life. Thank you for saving me and for giving me the gift of eternal life in Heaven with you. Amen.

**Comment by sindelio** [comment]
Respect for your faith
